services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    ports:
      - "${BACKEND_HTTPS_PORT}:${BACKEND_HTTPS_PORT}"
      - "${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"

volumes:
  db_data:
